lf_app/urls.py
'''URL / routing definition for the `loc` application.'''

from django.urls import path

from . import views

app_name = 'lf'

urlpatterns = [
    path('', views.LinkIndexView.as_view(), name='index'),

    path('link/<int:pk>/', views.LinkDetailView.as_view(), name='link'),
    path('links/tagged/<str:tag>/', views.TaggedLinksView.as_view(), name='links_tagged'),
    path('link/create/', views.LinkCreateView.as_view(), name='link_create'),
    path('link/edit/<int:pk>/', views.LinkUpdateView.as_view(), name='link_edit'),
    path('link/delete/<int:pk>/', views.LinkDeleteView.as_view(), name='link_delete'),
    path('link/open/<int:pk>/', views.link_open, name='link_open'),


    path('tags', views.tags_list, name='tags_list'),


    path('search/', views.link_search, name='search'),

    path('find_meta', views.find_metadata, name='find_meta'),

    path('info/', views.info, name='info'),
]

lf_project/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('lf_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    # For development host media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lf_app/models.py
'''Model definition for the `loc` application.'''

from django.core.exceptions import ValidationError
from django.conf import settings
from django.urls import reverse
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy

from taggit.managers import TaggableManager

class Link(models.Model):
    url = models.URLField(
        max_length=1024,
        default='')

    title = models.CharField(
        max_length=1024,
        default='')

    notes = models.TextField(
        default='',
        blank=True)

    created_on = models.DateTimeField(auto_now_add=True)

    updated_on = models.DateTimeField(auto_now=True)

    follow_count = models.PositiveIntegerField(default=0)

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)

    tags = TaggableManager()

    def __str__(self):
        return f'Link: {self.title}'


    def get_absolute_url(self):
        return reverse('lf:link', args=[self.id])


    def get_tags(self):
        return self.tags.order_by('name')

lf_app/forms.py
'''Forms used in the `loc` application.'''

from django import forms
from django.shortcuts import redirect

from .models import Link


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['url', 'title', 'notes', 'tags']

lf_app/views.py
'''Views for the `loc` app'''

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .models import Link
from .forms import LinkForm

from lf_project import versioninfo

from web_meta import find_website_meta

def index(request):
    return render(request, 'lf_app/index.html')


def info(request):
    '''View to show application info.'''

    context = {
        'info': versioninfo,
    }

    return render(request, 'lf_app/info.html', context)


# run this view in a transaction to be sure to count followed links correctly
@transaction.atomic
def link_open(request, pk):
    link = get_object_or_404(Link, pk=pk)

    link.follow_count += 1
    link.save()

    return redirect(link.url)


class LinkIndexView(ListView):
    '''Index list of top-level plans'''

    # order links by create date
    queryset = Link.objects.order_by('-created_on')
    context_object_name = 'links'
    paginate_by = 10


class TaggedLinksView(ListView):
    context_object_name = 'links'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['tag'] = self.kwargs['tag']

        return context

    def get_queryset(self):
        qs = Link.objects.filter(tags__name__in=[self.kwargs['tag']]).order_by('-created_on')

        return qs


class LinkDetailView(DetailView):
    '''Show details of a link.'''

    model = Link
    context_object_name = 'link'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        related_links = self.object.tags.similar_objects()

        context['related'] = related_links

        return context


class LinkCreateView(CreateView):
    '''View to create a new link.'''

    model = Link
    form_class = LinkForm

    def get_initial(self):
        '''Set initial data if we get it through the get request.'''

        initial = super().get_initial()

        initial['url'] = self.request.GET.get('url', '')
        initial['title'] = self.request.GET.get('title', '')

        return initial


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()

        # for saving the tags
        form.save_m2m()

        return redirect(self.get_success_url())



class LinkUpdateView(UpdateView):
    '''View to edit a link.'''

    model = Link
    form_class = LinkForm


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()

        # for saving the tags
        form.save_m2m()

        return redirect(self.get_success_url())


class LinkDeleteView(DeleteView):
    '''Delete a link.'''
    model = Link
    success_url = reverse_lazy('lf:index')


def link_search(request):
    term_str = request.GET.get('term', '')

    terms = term_str.split(' ')

    tags = [term[4:] for term in terms if term.startswith('tag:')]
    words = [term for term in terms if not term.startswith('tag:')]

    qs = Link.objects

    for word in words:
        qs = qs.filter(Q(title__icontains=word) | Q(notes__icontains=word)) \

    for tag in tags:
        qs = qs.filter(tags__name__in=[tag])

    qs.distinct()

    links = qs.order_by('-created_on')

    context = {
        'links': links,
    }

    return render(request, 'lf_app/link_list.html', context)


def tags_list(request):
    tags = Link.tags.order_by('name').all()

    context = {
        'tags': tags,
    }

    return render(request, 'lf_app/tags_list.html', context)


def find_metadata(request):
    url = request.GET.get('url', '')

    if not 'url':
        raise Http404()

    metadata = find_website_meta(url)

    return JsonResponse(metadata)

lf_app/templates/lf_app/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block content %}
This is the index.
{% endblock %}

lf_app/templates/lf_app/info.html
{% extends 'base.html' %}

{% block title %}Info{% endblock %}


{% block content %}

<h2>Bookmarklet</h2>

<p>
  Please drag&amp;drop the following bookmarklet into your bookmark bar:
</p>

<p class="text-center">
  <a class="badge badge-primary"
     href="{% include 'lf_app/macros/bootmarklet.js' with siteurl=siteurl %}"><span class="h1">linker_file</span></a>
</p>


<h2>Version Information</h2>

<div class="row mt-4">
  <table class="table table-hover col-6">
    <tr>
      <th scope="row">Application Version</th>
      <td>{{ info.VERSION }}</td>
    </tr>
    <tr>
      <th scope="row">Git Tag</th>
      <td>{{ info.GIT_TAG }}</td>
    </tr>
    <tr>
      <th scope="row">Git Hash</th>
      <td>{{ info.GIT_HASH }}</td>
    </tr>
    <tr>
      <th scope="row">Build Date</th>
      <td>{{ info.BUILD_DATE }}</td>
    </tr>
    <!--<tr scope="row">
      <th>Build Host</th>
    <td>{{ info.BUILD_HOST }}</td>
    </tr>-->
  </table>
</div>

<h2>Application Information</h2>

<div class="row mt-4">
  <table class="table table-hover col-6">
    <tr>
      <th scope="row">Developed by</th>
      <td>Andreas Schröder &lt;<a href="mailto:andreas@a-netz.de">andreas@a-netz.de</a>&gt;</td>
    </tr>
    <tr>
      <th scope="row">Source Code</th>
      <td><a href="https://github.com/motlib/dbloc">https://github.com/motlib/dbloc</a></td>
    </tr>
    <tr>
      <th scope="row">License</th>
      <td><a href="https://www.gnu.org/licenses/gpl-3.0.en.html">GNU General Public License v3</a></td>
    </tr>
  </table>
</div>
{% endblock %}

lf_app/templates/lf_app/link_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Link Detail{% endblock %}

{% block content %}

Do you really want to delete the link '{{ link.title}}'?

<form method="post">
  {% csrf_token %}

  <button class="btn btn-danger" type="submit">Delete!</button>
  <a class="btn btn-secondary" href="{% url 'lf:link' link.id %}">Cancel</a>

{% endblock %}

lf_app/templates/lf_app/link_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Link Detail{% endblock %}

{% block content %}

<table class="table">
  <tr>
    <th>
      Title
    </th>
    <td>
      {{ link.title }}
    </td>
  </tr>

  <tr>
    <th>
      URL
    </th>
    <td>
      <a href="{{ link.url }}">{{ link.url }}</a>
    </td>
  </tr>

  <tr>
    <th>
      Notes
    </th>
    <td>
      {{ link.notes }}
    </td>
  </tr>

  <tr>
    <th>
      Dates
    </th>
    <td>
      Created on {{ link.created_on }}, last update on {{ link.updated_on }}
    </td>
  </tr>


  <tr>
    <th>
      Owner
    </th>
    <td>
      {{ link.owner }}
    </td>
  </tr>

</table>

<p>
  <a class="btn btn-primary" href="{% url 'lf:link_edit' link.id %}">Edit</a>
  <a class="btn btn-danger" href="{% url 'lf:link_delete' link.id %}">Delete</a>

</p>


<h2>Related Links</h2>
{% for link in related %}
{% include 'lf_app/macros/link_card.html' with link=link %}
{% endfor %}


{% endblock %}

lf_app/templates/lf_app/link_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}

{% block title %}Edit Link{% endblock %}

{% block content %}

<p>
  <form method="post">
  {% csrf_token %}

  {% include 'lf_app/macros/form_errors.html' with form=form %}

  <div class="form-row">
    <div class="col">
      {{ form.url | as_crispy_field }}
    </div>
  </div>

  <div class="form-row">
    <div class="col-6">
      {{ form.title | as_crispy_field }}
    </div>
    <div class="col-6">
      {{ form.tags | as_crispy_field }}
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      {{ form.notes | as_crispy_field }}
    </div>
  </div>

  <button class="btn btn-primary" type="submit">Submit</button>
  <a class="btn btn-secondary" href="{% url 'lf:index' %}">Cancel</a>
</form>
</p>

<div class="row">
  <div class="col-3">
    <button id="btn_web_meta"
            class="btn btn-primary"
            type="button">Retrieve Metadata</button>
  </div>
  <div class="col-9">
    <div id="lb_status"></div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'lf_app/js/web_meta.js' %}"></script>
{% endblock %}

lf_app/templates/lf_app/link_list.html
{% extends 'base.html' %}


{% block title %}Latest Links{% endblock %}

{% block content %}

{% if tag %}
<p>
  Results for tag:
  <a class="badge badge-primary"
     href="{% url 'lf:links_tagged' tag %}">{{ tag }}</a>
</p>
{% endif %}


{% for link in links %}
{% include 'lf_app/macros/link_card.html' with link=link %}
{% endfor %}

{% include 'pagination.html' with page_obj=page_obj %}

{% endblock %}

lf_app/templates/lf_app/macros/form_errors.html
{# show form errrors as alerts #}
{% if form.non_field_errors %}
<div class="alert alert-block alert-danger">
  <ul class="list-unstyled m-0">
    {% for error in form.non_field_errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}

lf_app/templates/lf_app/macros/link_card.html
<div class="card mt-3">
  <div class="card-header">
    <a class="h5 card-title" href="{% url 'lf:link_open' link.id %}">{{link.title}}</a>
  </div>
  <div class="card-body">
    <div class="card-text">
      {% if link.notes %}
      <p>{{ link.notes }}</p>
      {% endif %}

      <div class="text-muted">
        {% with link.get_tags as tags %}
        {% if tags %}
        Tags:
        {% for tag in tags %}
        <a href="{% url 'lf:links_tagged' tag.name %}" class="badge badge-primary">{{tag.name}}</a>
        {% endfor %}
        {% endif %}<br />
        {% endwith %}
        Created: {{ link.created_on }}, updated: {{ link.updated_on }}<br />
        Followed: {{ link.follow_count }}
      </div>

      <a class="btn-sm btn-primary" href="{% url 'lf:link' link.id %}">Info</a>
      <a class="btn-sm btn-primary" href="{% url 'lf:link_edit' link.id %}">Edit</a>
    </div>
  </div>
</div>

lf_app/templates/lf_app/tags_list.html
{% extends 'base.html' %}

{% block title %}Tags{% endblock %}

{% block content %}
{% for tag in tags %}
<a class="badge badge-primary" href="{% url 'lf:links_tagged' tag %}">{{ tag }}</a>
{% endfor %}

{% include 'pagination.html' with page_obj=page_obj %}

{% endblock %}

lf_project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" style="font-size: 10pt;">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
          href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'css/style.css' %}">

    <title>linker_file</title>
  </head>

  <body>
    {% include 'navbar.html' %}

    <main id="content" class="container mt-5" role="main">
      <h2>{% block title %}{% endblock %}</h2>

      {% block content %}{% endblock %}
    </main>

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

lf_project/templates/navbar.html
{# main navigation bar fragment #}

{% load static %}

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'lf:index' %}">linker_file</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarsExample03" aria-controls="navbarsExample03"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="navbar-nav mr-auto">

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lf:link_create' %}">
          <img src="{% static 'plus-5-32.png' %}" width="16" height="16"> Add Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lf:tags_list' %}">Tags</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Administration</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Log out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Log in</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lf:info' %}">Info</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-md-0" method="GET" action="{% url 'lf:search' %}">
      <input class="form-control" type="text" name="term" placeholder="Search">
    </form>
  </div>
</nav>

lf_project/templates/pagination.html
{% load paginate_tags %}

{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    <li class="page-item" title="Go to first page">
      <a class="page-link"
         href="?page=1"
         aria-label="First">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for p in page_obj|paginate_range:3 %}
    <li class="page-item {% if p == page_obj.number %}active{% endif %}">
      <a class="page-link"
         href="?page={{ p }}">{{ p }}</a></li>
    {% endfor %}
    <li class="page-item" title="Go to last page">
      <a class="page-link"
         href="?page={{ page_obj.paginator.num_pages }}"
         aria-label="Last">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
  </nav>
{% endif %}